---
- name: Install go-agent
  apt:
    name: "{{ item }}"
    update_cache: 'yes'
    state: present
  become: true
  with_items:
    - locales
    - go-agent
    - nodejs

- name: add user go
  user:
    name: go
    state: present

- name: Upload go config
  template:
    src: go-agent
    dest: /etc/default/go-agent
    owner: go
  notify: restart go-agent
  become: true

- name: Upload cert
  copy:
    src: agent.jks
    dest: /var/lib/go-agent/conf/
    owner: go
  notify: restart go-agent
  become: true

- name: Upload trust cert
  copy:
    src: trust.jks
    dest: /var/lib/go-agent/conf/
    owner: go
  notify: restart go-agent
  become: true

- name: Add go user to docker group
  user:
    name: go
    group: docker
  become: true
