---
- name: Install go-agent
  apt:
    name: "{{ item }}"
    update_cache: 'yes'
    state: present
  become: true
  with_items:
    - locales
    - go-agent
    - nodejs
    - python-pip
    - sshpass
    - golang
    - go-dep

- name: Install Python packages
  pip:
    name: ["ansible", "minio", "molecule"]
    state: present

- name: add user go
  user:
    name: go
    state: present

- name: Change owner directories
  file:
    path: ["/usr/share/go-agent/", "/var/log/go-agent/"]
    owner: go
    group: go
    recurse: yes


- name: Upload go config
  template:
    src: wrapper-properties.conf.j2
    dest: /usr/share/go-agent/wrapper-config/wrapper-properties.conf
  notify: restart go-agent
  become: true

- name: Upload cert
  copy:
    src: agent.jks
    dest: /var/lib/go-agent/conf/
    owner: go
  notify: restart go-agent
  become: true

- name: Upload trust cert
  copy:
    src: trust.jks
    dest: /var/lib/go-agent/conf/
    owner: go
  notify: restart go-agent
  become: true

- name: Add go user to docker group
  user:
    name: go
    group: docker
  become: true
