---
- name: Create Directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /var/local/data/godata
    - /var/local/goserver/prod/

- name: Upload docker compose
  template:
    src: docker-compose-goserver.yml.j2
    dest: /var/local/goserver/prod/docker-compose.yml

- name: Run docker compose
  docker_service:
    project_src: /var/local/goserver/prod/
    state: present
