---
- name: Install go-server
  apt:
    name: "{{ item }}"
    update_cache: 'yes'
    state: present
  become: true
  with_items:
    - go-server=18.9.0*

- name: Enable service go-server
  systemd:
    enabled: true
    name: go-server
  become: true

- name: Start service go-server
  systemd:
    state: started
    name: go-server
  become: true
