---
# tasks file for ansible-role-gocd
- name: add gocd repository
  copy:
    src: gocd.list
    dest: /etc/apt/sources.list.d/gocd.list
  become: true

- name: add repository key
  get_url:
    url: https://download.gocd.io/GOCD-GPG-KEY.asc
    dest: "/tmp/GOCD-GPG-KEY.asc"
  become: true

- name: add key
  apt_key:
    file: /tmp/GOCD-GPG-KEY.asc
    state: present
  become: true

- include_tasks: go-server.yml
  when: "'gocd-server' in group_names"

- include_tasks: go-agent.yml
  when: "'gocd-agents' in group_names"
