---
# tasks file for ansible-role-gocd
- name: add gocd repository
  copy:
    src: gocd.list
    dest: /etc/apt/sources.list.d/gocd.list
    mode: '0600'
  become: true

- name: add repository key
  get_url:
    url: https://download.gocd.io/GOCD-GPG-KEY.asc
    dest: "/tmp/GOCD-GPG-KEY.asc"
  become: true

- name: add key
  apt_key:
    file: /tmp/GOCD-GPG-KEY.asc
    state: present
  become: true

- name: Install openjdk
  apt:
    name: openjdk-11-jre
    state: present
    update_cache: true

- include_tasks: go-server.yml
  when: "'gocd_server' in group_names"

- include_tasks: go-agent.yml
  when: "'gocd_agents' in group_names"
