---
- name: Converge
  hosts: all
  vars:
    - GOCD_SERVER: "https://molecule-gocd-server:8154/go"
  tasks:
    - name: "Include my-new-role"
      include_role:
        name: "ansible-role-gocd"
