---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
        yamllint .
        ansible-lint
        flake8
platforms:
  - name: "molecule-gocd-server"
    image: "asg1612/docker-systemd"
    privileged: true
    required: 'True'
    exposed_ports:
      - "8153:8153"
      - "8154:8154"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    command: /lib/systemd/systemd
    groups:
      - gocd-server
  - name: molecule-gocd-agent
    image: asg1612/docker-systemd
    privileged: true
    required: 'True'
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    command: /lib/systemd/systemd
    groups:
      - gocd-agents
    links:
      - molecule-gocd-server:gocd-server
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
