---
on:  # yamllint disable-line rule:truthy
  push:

jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - uses: gofrolist/molecule-action@v2
          with:
            molecule_command: test
            molecule_args: --scenario-name github
